# Generated by Django 4.2.5 on 2023-09-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("splitwise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="balance_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
