# Generated by Django 4.2.5 on 2023-09-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "splitwise",
            "0002_alter_balance_balance_id_alter_expense_expense_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="expense_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="splitwise.expense",
            ),
        ),
    ]
